### ISSUE TITLE
Resume parsing failed! "Error 500 - Could not parse resume"

### ISSUE THREAD

**Issue by DevBoopathi** [KnlnKS/resume-parser#12]
error - uncaughtException: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at _res.setHeader (C:\Users\Boopathi\S1-resume-parser\node_modules\next\dist\server\base-server.js:128:24)
    at Object.sendEtagResponse (C:\Users\Boopathi\S1-resume-parser\node_modules\next\dist\server\send-payload\index.js:29:13)
    at sendData (C:\Users\Boopathi\S1-resume-parser\node_modules\next\dist\server\api-utils\node.js:172:27)
    at apiRes.send (C:\Users\Boopathi\S1-resume-parser\node_modules\next\dist\server\api-utils\node.js:350:31)
    at Command.eval [as callback] (webpack-internal:///(api)/./pages/api/events.js:23:36)
    at RedisClient.flush_and_error (C:\Users\Boopathi\S1-resume-parser\node_modules\redis\index.js:310:29)
    at RedisClient.connection_gone (C:\Users\Boopathi\S1-resume-parser\node_modules\redis\index.js:533:14)
    at Socket.<anonymous> (C:\Users\Boopathi\S1-resume-parser\node_modules\redis\index.js:227:14) {       
  code: 'ERR_HTTP_HEADERS_SENT'
}

**Comment by VedantMadane** [comment]
An "Error 500" is a general message indicating that something went wrong on the server (the computer system hosting the application). It's like a generic "something broke" message.
